### ISSUE TITLE
Publish in NPM?

### ISSUE THREAD

**Issue by necramirez** [stevenh77/drop-ng#21]
I have an NPM-only front-end build right now, and I don't want to add Bower just for this.

**Comment by stevenh77** [comment]
No sorry but may I suggest just including the source file as it's not very big and shouldn't get many updates at this stage.

**Comment by necramirez** [comment]
I settled on adding this Github repo directly to my NPM dependencies -- I wanted it in there so I can `require()` it with Browserify.
