### ISSUE TITLE
Add support for tetherOptions

### ISSUE THREAD

**Issue by pietschy** [stevenh77/drop-ng#7]
Hi there, 

I need to provide to be able to offset the drop from the parent element and would like to be able to pass in tetherOptions as per http://github.hubspot.com/drop/#-tetheroptions-

Happy to create in a pull request if you like.

Cheers

**Comment by stevenh77** [comment]
Hi Andrew, sounds good!  Please fork and pull then I'll review and merge straight away - cheers.

**Comment by stevenh77** [comment]
Don't forget to create an example page and protractor test to show it working.  Let me know if you need a hand with anything, thanks Steve

**Comment by pietschy** [comment]
Hi Steven,  I've created the pull request.  Let me know if you need changes or improvements.

Just a note, I'm getting `Error: No provider for "framework:jasmine"!` when running the karma tests.  I hunted around but none of the solutions I found worked for me.

**Comment by pietschy** [comment]
Hi Steven,

Is there any chance of getting a new dot release with the tether options included? (I'm currently using rails-assets.org to suck things down and it'd make it a bit easier for me.)
Thanks & cheers

**Comment by stevenh77** [comment]
Release created, v0.1.1
